# Generated by Django 3.1.6 on 2021-04-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webspotify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite_artist',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='favourite_genre',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='favourite_song',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='favourite_artist',
            name='spotify_username',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='favourite_genre',
            name='spotify_username',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='favourite_song',
            name='spotify_username',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='django_username',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_username',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
