# Generated by Django 3.1.6 on 2021-04-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webspotify', '0002_auto_20210410_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Sp_User',
        ),
    ]
