# Generated by Django 3.1.6 on 2021-05-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webspotify', '0005_auto_20210511_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite_artist',
            name='spotify_username',
            field=models.ForeignKey(default='usern', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='webspotify.sp_user'),
        ),
        migrations.AlterField(
            model_name='favourite_genre',
            name='spotify_username',
            field=models.ForeignKey(default='usern', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='webspotify.sp_user'),
        ),
        migrations.AlterField(
            model_name='favourite_song',
            name='spotify_username',
            field=models.ForeignKey(default='usern', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='webspotify.sp_user'),
        ),
        migrations.AlterField(
            model_name='sp_user',
            name='spotify_username',
            field=models.CharField(default='usern', max_length=50),
        ),
    ]
