# Generated by Django 3.1.6 on 2021-05-12 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webspotify', '0007_auto_20210512_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite_artist',
            name='artist_id',
        ),
        migrations.RemoveField(
            model_name='favourite_artist',
            name='position',
        ),
        migrations.RemoveField(
            model_name='favourite_artist',
            name='spotify_username',
        ),
        migrations.RemoveField(
            model_name='favourite_artist',
            name='term',
        ),
        migrations.RemoveField(
            model_name='favourite_genre',
            name='genre_name',
        ),
        migrations.RemoveField(
            model_name='favourite_genre',
            name='position',
        ),
        migrations.RemoveField(
            model_name='favourite_genre',
            name='spotify_username',
        ),
        migrations.RemoveField(
            model_name='favourite_genre',
            name='term',
        ),
        migrations.RemoveField(
            model_name='favourite_song',
            name='position',
        ),
        migrations.RemoveField(
            model_name='favourite_song',
            name='song_id',
        ),
        migrations.RemoveField(
            model_name='favourite_song',
            name='spotify_username',
        ),
        migrations.RemoveField(
            model_name='favourite_song',
            name='term',
        ),
        migrations.AddField(
            model_name='favourite_artist',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='favourite_artist',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='favourite_artist',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)'),
        ),
        migrations.AddField(
            model_name='favourite_artist',
            name='user',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favourite_genre',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='favourite_genre',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='favourite_genre',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)'),
        ),
        migrations.AddField(
            model_name='favourite_genre',
            name='user',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favourite_song',
            name='artist_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='favourite_song',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='favourite_song',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='favourite_song',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)'),
        ),
        migrations.AddField(
            model_name='favourite_song',
            name='user',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
