# Generated by Django 3.1.6 on 2021-05-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webspotify', '0008_auto_20210512_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite_artist',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='favourite_genre',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='favourite_song',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
