# Generated by Django 3.1.6 on 2021-05-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webspotify', '0009_auto_20210512_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite_artist',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Rating (stars)'),
        ),
        migrations.AlterField(
            model_name='favourite_genre',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Rating (stars)'),
        ),
        migrations.AlterField(
            model_name='favourite_song',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, verbose_name='Rating (stars)'),
        ),
    ]
