# Generated by Django 3.2.3 on 2021-05-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webspotify', '0010_auto_20210517_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite_song',
            name='genre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
